### ISSUE TITLE
Mobile: Save Session Date From/To filter

### ISSUE THREAD

**Issue by fcoutellier** [sap-labs-france/ev-mobile#233]
In Statistics and Sessions
- [x] Fix the bug when the filter pop is displayed and one of the date is clicked
- [x] Check the dark theme to adjust the color of the control
- [x] Check if the calendar can be displayed right away (usability)
- [x] Save selected dates in the secured storage + reload it when the app starts 
- [x] Fix bug when filtering by dates two times in a row does not work
- [x] Fix bug when chosing "My Sessions", dates in modal filter disappear (Invalid Date) instead of switching back to default

**Comment by AlixH** [comment]
Test cases in **Sessions History** : 

- [ ]  The datepicker opens when clicking on either start date or end date inside the filters modal 

- [ ] The datepicker colors changes according to the app current theme 

- [ ] One can filter by dates several times in a row and see each time the updated sessions list

- [ ]  When current user has 0 sessions in the history, selecting "My Sessions" show the current date for both start date and end date in the filter modal. Plus, all other dates are disabled inside the datepicker

- [ ] At opening of the screen with the "My Sessions" button on for a user with 0 sessions, filtering by dates does nothing

- [ ] At opening of the screen, last used dates are still picked in the filter modal and the datepicker. The sessions list also matches the initial filters

- [ ] When switching between "My Sessions" and all sessions, the start date and end date are respectively set to the minimum possible date and the maximum possible date

- [ ] When writing in the text input, the min and max allowed dates for the filter are changed to fit the new search criteria. Also, the previously chosen date range is changed accordingly to the new min and max.
