### ISSUE TITLE
Mobile > Initial Config: Propose the user to register a new tenant when no tenant is available

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-mobile#283]

**Comment by LucasBrazi06** [comment]
At start up, check the list of orgs
If none, propose to the user to scan the QR-Code to create one.
Once created, propose the user to register.

**Comment by LucasBrazi06** [comment]
After testing, fix the following issues:
- [ ] After successful tenant scan, message to register is displayed: propose instead of 'Close' and 'Yes' buttons, 'Sign In' and 'Sign Up'
  - When Sign In clicked: navigate to the login screen and prefill the tenant name
  - When Sign Up clicked: navigate to the Sign Up page (current behavior)
- [ ] In Sign Up page, if I click on 'Sign In' to go back to the login screen without registering, the tenant in the login screen should have the newly created tenant set
- [ ] When latest tenant is deleted in the list and you go back to login screen, both input fields user and password are still filled 
(they should be empty)
- [ ] Test, test, test... ;-)

**Comment by AlixH** [comment]
Re-tested !
