### ISSUE TITLE
Mobile > Billing - STRIPE - Add a Payment Method

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-mobile#289]
- [x] prio 1: Validate the behaviour of the react native beta library - Strong authentication should work properly when confirming a card setup
- [x] Allow to add new payment method
Find a (PCI compliant ?) react-native library for Stripe
- [x] Fetch billing settings (to get the publishableKey) in order to properly initialize the Stripe layer 
- [x] Attach the latest payment method to the customer
- [x] Make sure the latest payment method becomes the default payment method of the customer
- [x] Display the list of user's payment methods 
(New screen for Users Navigator, navigate to Payment Methods when user is clicked). Provide an access via user's profile (canListUsers can be false)
- [ ] Provide the list of invoices (Home & SideBar accesses) (canListInvoices + isBillingActive)

**Comment by LucasBrazi06** [comment]
@AlixH To check with Claude (not yet ready at this time)

**Comment by ClaudeROSSI** [comment]
@LucasBrazi06 : I need to get the confirmation that the beta version of the stripe react native library behaves as expected when confirming a card setup. This is the main prerequisite. I do not expect any difficulties for the rest of the feature.

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 : I need to get the confirmation that the beta version of the stripe react native library behaves as expected when confirming a card setup. This is the main prerequisite. I do not expect any difficulties for the rest of the feature.

Ask @AlixH :-)
I need just to check on my side if we can compile and deliver it.

**Comment by ClaudeROSSI** [comment]
> > @LucasBrazi06 : I need to get the confirmation that the beta version of the stripe react native library behaves as expected when confirming a card setup. This is the main prerequisite. I do not expect any difficulties for the rest of the feature.
> 
> Ask @AlixH :-)
> I need just to check on my side if we can compile and deliver it.

Right. That's the point. I need Alix to start soon enough to validate that the 3d secure authentication works properly. If we face difficulties on this it will be a showstopper.

**Comment by ClaudeROSSI** [comment]
@LucasBrazi06 : Some good news - 3D Secure redirection has been tested on IOS. The flow works as expected.
Still a lot to do ... but no showstoppers!

![image](https://user-images.githubusercontent.com/26900551/117148554-9c211900-adb6-11eb-9a45-53f58608fcc4.png)

![image](https://user-images.githubusercontent.com/26900551/117148578-a4795400-adb6-11eb-95e8-5602181730c9.png)
  
![image](https://user-images.githubusercontent.com/26900551/117148611-ad6a2580-adb6-11eb-9a5e-62de78bdd3c0.png)

**Comment by AlixH** [comment]
<img width="477" alt="Screenshot 2021-05-06 at 16 02 23" src="https://user-images.githubusercontent.com/32574035/117311507-8712bb80-ae84-11eb-81fa-9250b84c38a5.png">

**Comment by AlixH** [comment]
Tested today: 

- [ ] Dark/Light modes on Android/IOS
- [ ] Regular Card creation (no 3DS) on both OS
- [ ] 3DS Card creation on both OS
- [ ] Card input field validation
