### ISSUE TITLE
Support: Create a new screen to report an issue to the support team

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-mobile#31]

**Comment by LucasBrazi06** [comment]
Dups

**Comment by Skyrix06** [comment]
- [ ] Create report error button in the sidebar
- [ ] Create the screen
- [ ] Handle mandatory field
- [ ] Create report error button in the connector details screen
- [ ] Display in the subject field the charging station and connector when the user access to the report error screen on the connector details screen
- [ ] Save the mobile when report error send
- [ ] Send the information to the backend

**Comment by AlixH** [comment]
> * [x]  Create report error button in the sidebar
> * [x]  Create the screen
> * [x]  Handle mandatory field
> * [x]  Create report error button in the connector details screen
> * [x]  Display in the subject field the charging station and the connector when the user access to the report error screen on the connector details screen
> * [x]  Save the mobile when report error send
> * [x]  Send the information to the backend

@LucasBrazi06 do you now what mobile is ?  The name is not intuitive if it's a phone number

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 do you now what mobile is ? The name is not intuitive if it's a phone number

Yes this is the mobile phone number :-)
