### ISSUE TITLE
Sessions > Start : Start a session by selecting your Car and Badge (and user for Admin)

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-mobile#35]
- [x] Provide the list of Users (canListUsers) + PR
- [x] Provide the list of Badges (canListTags) + PR
- [x] Provide the list of Cars (canListCars) if Car component is active + PR
- [x] [Low Prio] Navigate from Cars to Users + PR
- [x] Check all the screens on iPad and adjust the style + PR
- [x] Create in the Connector details a view that will replace the current connector infos with
  - [x] A User selection (only for admins) + PR
  - [x] A Badges selection + PR
  - [x] A Car selection + PR
- [x] Test the start of a transaction by passing these informations

**Comment by LucasBrazi06** [comment]
@AlixH requested changes in our PR which I merged to easier review the rest.

**Comment by LucasBrazi06** [comment]
@AlixH check my comments in the merged PR

**Comment by LucasBrazi06** [comment]
@AlixH Double check all the screens of the app in the iPad and adjust the style accordingly:

![image](https://user-images.githubusercontent.com/25266945/112721316-7f660b80-8f03-11eb-8638-0488b76bba05.png)

**Comment by AlixH** [comment]
What do you mean by Car component is active ? 
Only list the active cars ?

**Comment by LucasBrazi06** [comment]
> What do you mean by Car component is active ?
> Only list the active cars ?

Put your comment close to mine otherwise I won't have the context ;-).
Car component is active in the tenant:
![image](https://user-images.githubusercontent.com/25266945/112734678-93cbf780-8f47-11eb-8693-8b3fe158006b.png)

Check the SecurityProvider, for instance to check if the Org is active:

```
  public isComponentOrganizationActive(): boolean {
    return this.isComponentActive(TenantComponents.ORGANIZATION);
  }
```

**Comment by LucasBrazi06** [comment]
@AlixH No PR is attached to this issue ;-)

**Comment by AlixH** [comment]
The next one is coming !
