### ISSUE TITLE
Mobile: Inactive Site / Site Area status should have inactive status

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-mobile#364]
- Display inactive status
- Rename 'Inactive' to 'Not Charging'
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/643b8d32-b33a-47c3-b605-afcde5b700c3)

**Comment by AlixH** [comment]
@LucasBrazi06 What do you mean by the first bullet point ?

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 What do you mean by the first bullet point ?

I think I did it already, you can ignore it.
Just rename Inactive to Not Charging and use the following order: Available, Unavailable, Charging, Not Charging
Thanks
