### ISSUE TITLE
Mobile > Badge: Add user, default and a generic icon

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-mobile#365]
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/f0c382d1-6a23-437c-a970-a1b088b20f5f)

**Comment by AlixH** [comment]
@LucasBrazi06  Does the new style still requires a generic icon ?

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 Does the new style still requires a generic icon ?

Yep.
Btw, the ID is no longer displayed, only visualID

**Comment by AlixH** [comment]
> > @LucasBrazi06 Does the new style still requires a generic icon ?
> 
> Yep.
> Btw, the ID is no longer displayed, only visualID

I am afraid the icon will take too much space, here it is still small
<img width="481" alt="Screenshot 2021-07-08 at 17 11 54" src="https://user-images.githubusercontent.com/32574035/124946978-c047e300-e00f-11eb-8717-dd9ef7cdc300.png">

**Comment by LucasBrazi06** [comment]
> I am afraid the icon will take too much space, here it is still small

Yes you're right.
Have you checked the design on other apps ?

**Comment by AlixH** [comment]
> > I am afraid the icon will take too much space, here it is still small
> 
> Yes you're right.
> Have you checked the design on other apps ?

Chargemap has a single pass, Smoov has a really poor design, I am trying to figure something out

**Comment by LucasBrazi06** [comment]
ChargePoint and Shell

**Comment by AlixH** [comment]
Well, one common point is that fonts are smaller, so I tried something with reduced fonts and I think it looks better :)

<img width="923" alt="Screenshot 2021-07-08 at 18 37 44" src="https://user-images.githubusercontent.com/32574035/124962718-40c21000-e01f-11eb-9490-bd65959af430.png">

The icon I have chosen is very similar to the one in Shell Recharge app

**Comment by LucasBrazi06** [comment]
Mine is better :-P
![2021-07-08_19-18-36](https://user-images.githubusercontent.com/25266945/124964451-533d4900-e021-11eb-8a48-265ebcf936f4.png)

**Comment by AlixH** [comment]
> Mine is better :-P
> ![2021-07-08_19-18-36](https://user-images.githubusercontent.com/25266945/124964451-533d4900-e021-11eb-8a48-265ebcf936f4.png)

Where did you get it ?

**Comment by LucasBrazi06** [comment]
> Where did you get it ?

I made it :)
