### ISSUE TITLE
Check if new version is available and jump to the corresponding store to update the app

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-mobile#404]

**Comment by AlixH** [comment]
Should it be done at launch ?

**Comment by LucasBrazi06** [comment]
> Should it be done at launch ?

Yes if it's possible.

**Comment by rccess** [comment]
update button is not working , no action on click : having bug , please look from your side once : sidebar menu update button working fine, but on opening app update button not working

**Comment by LucasBrazi06** [comment]
@AlixH Could you check?
Thanks!
